name: domain-of-the-day
description: Paper Plugin sending different MOTDs or Messages depending on the Domain used by the Player
version: '${project.version}'
authors:
  - Velyn
main: me.velyn.domain.dotd.DotDMain
api-version: '1.20'
permissions:
  dotd.admin:
    description: Gives Access to the Domain of the Day Administration Command