name: domain-deprecator
description: Paper Plugin sending messages depending on the Domain used for Joining
version: '${project.version}'
authors:
  - Velyn
main: de.nmadev.domain.deprecator.DomainDeprecator
api-version: '1.20'
permissions:
  domain-deprecator.admin:
    description: Gives Access to the Plugins Administration Command